version: '3.8'

services:
  web:
    build: .
    command: "yarn start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
    links:
      - db:db
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'ppaa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  node_modules:
  db:
