version: '3.8'

services:
  web:
    build: .
    command: "yarn start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
